datasets:
  url1 :
    - rgbd_dataset_freiburg1_desk 
    - https://vision.in.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_desk.tgz
  url2 :
    - rgbd_dataset_freiburg3_sitting_static 
    - https://vision.in.tum.de/rgbd/dataset/freiburg3/rgbd_dataset_freiburg3_sitting_static.tgz

select:
  - url2